apiVersion: v1
kind: ConfigMap
metadata:
  name: users-config
  namespace: users
  labels:
    app: users
data:
  ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
  ASPNETCORE_URLS: "http://+:80"
  AWS__Region: ${AWS_REGION}
  AWS__AccountId: ${AWS_ACCOUNT_ID}
  DatabaseProvider: "PostgreSql"
  Jwt__ExpirationTimeHour: "5"
  Jwt__IncreaseExpirationTimeMinutes: "20"
  PATH_BASE: "/api/users"