apiVersion: v1
kind: Secret
metadata:
  name: usuarios-secrets
  namespace: usuarios
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "${DB_VAL}"
  Jwt__Key: "7G+H65bLToXxqzPvj7+q0oQUlxJp1WvdOU3nv3ArA1s="
  AWS__AccessKey: "${KEY_ID}"
  AWS__SecretKey: "${KEY_SECRET}"
  AWS__SessionToken: "${KEY_TOKEN}"
